<?php
/**
 * Ice data provider implementation redis class
 *
 * @link http://www.iceframework.net
 * @copyright Copyright (c) 2014 Ifacesoft | dp <denis.a.shestakov@gmail.com>
 * @license https://github.com/ifacesoft/Ice/blob/master/LICENSE.md
 */

namespace Ice\Data\Provider;

use Ice\Core\Data_Provider;
use Ice\Core\Exception;

/**
 * Class Redis
 *
 * Data provider for redis storage
 *
 * @see Ice\Core\Data_Provider
 *
 * @author dp <denis.a.shestakov@gmail.com>
 *
 * @package Ice
 * @subpackage Data_Provider
 *
 * @version 0.0
 * @since 0.0
 */
class Redis extends Data_Provider
{
    /**
     * Get data from data provider by key
     *
     * @param string $key
     * @return mixed
     *
     * @author dp <denis.a.shestakov@gmail.com>
     *
     * @version 0.0
     * @since 0.0
     */
    public function get($key = null)
    {
        return $this->getConnection()->get($this->getFullKey($key));
    }

    /**
     * Return data provider redis connection
     *
     * @return \Redis
     *
     * @author dp <denis.a.shestakov@gmail.com>
     *
     * @version 0.0
     * @since 0.0
     */
    public function getConnection()
    {
        return parent::getConnection(); // TODO: Change the autogenerated stub
    }

    /**
     * Set data to data provider
     *
     * @param string $key
     * @param $value
     * @param null $ttl
     * @return mixed setted value
     *
     * @author dp <denis.a.shestakov@gmail.com>
     *
     * @version 0.0
     * @since 0.0
     */
    public function set($key, $value, $ttl = null)
    {
        if ($ttl == -1) {
            return $value;
        }

        if ($ttl === null) {
            $options = $this->getOptions(__CLASS__);
            $ttl = $options['ttl'];
        }

        return $this->getConnection()->set($this->getFullKey($key), $value, $ttl) ? $value : null;
    }

    /**
     * Return connection options
     *
     * @param $class
     * @return array
     *
     * @author dp <denis.a.shestakov@gmail.com>
     *
     * @version 0.0
     * @since 0.0
     */
    protected function getOptions($class)
    {
        return array_merge(['host' => 'localhost', 'port' => 6379], parent::getOptions($class));
    }

    /**
     * Delete from data provider by key
     *
     * @param string $key
     * @param bool $force if true return boolean else deleted value
     * @throws Exception
     * @return mixed|boolean
     *
     * @author dp <denis.a.shestakov@gmail.com>
     *
     * @version 0.0
     * @since 0.0
     */
    public function delete($key, $force = true)
    {
        if ($force) {
            $this->getConnection()->delete($this->getFullKey($key));
            return true;
        }

        $value = $this->get($key);

        $this->getConnection()->delete($this->getFullKey($key));

        return $value;
    }

    /**
     * Increment value by key with defined step (default 1)
     *
     * @param $key
     * @param int $step
     * @throws Exception
     * @return mixed new value
     *
     * @author dp <denis.a.shestakov@gmail.com>
     *
     * @version 0.0
     * @since 0.0
     */
    public function inc($key, $step = 1)
    {
        throw new Exception('Implement inc() method.');
    }

    /**
     * Decrement value by key with defined step (default 1)
     *
     * @param $key
     * @param int $step
     * @throws Exception
     * @return mixed new value
     *
     * @author dp <denis.a.shestakov@gmail.com>
     *
     * @version 0.0
     * @since 0.0
     */
    public function dec($key, $step = 1)
    {
        throw new Exception('Implement dec() method.');
    }

    /**
     * Flush all stored data
     *
     * @author dp <denis.a.shestakov@gmail.com>
     *
     * @version 0.0
     * @since 0.0
     */
    public function flushAll()
    {
        File::getLogger()->info(['Trying remove {$0}', $this->getKeyPrefix() . '*']);
        $this->getConnection()->delete($this->getConnection()->getKeys($this->getKeyPrefix() . '*'));
    }

    /**
     * Connect to data provider
     *
     * @param $connection
     * @return boolean
     *
     * @author dp <denis.a.shestakov@gmail.com>
     *
     * @version 0.0
     * @since 0.0
     */
    protected function connect(&$connection)
    {
        $options = $this->getOptions(__CLASS__);

        $connection = new \Redis();

        $isConnected = $connection->connect($options['host'], $options['port']);

        if (!$isConnected) {
            $connection->getLastError();
        }

        if (function_exists('igbinary_serialize')) {
            $connection->setOption(\Redis::OPT_SERIALIZER, \Redis::SERIALIZER_IGBINARY);
        } else {
            $connection->setOption(\Redis::OPT_SERIALIZER, \Redis::SERIALIZER_PHP);
        }

        $connection->setOption(\Redis::OPT_PREFIX, 'ice/');

        return $isConnected;

    }

    /**
     * Close connection with data provider
     *
     * @param $connection
     * @return boolean
     *
     * @author dp <denis.a.shestakov@gmail.com>
     *
     * @version 0.0
     * @since 0.0
     */
    protected function close(&$connection)
    {
        $this->getConnection()->close();
        return true;
    }

    /**
     * Return keys by pattern
     *
     * @param string $pattern
     * @return array
     *
     * @author dp <denis.a.shestakov@gmail.com>
     *
     * @version 0.0
     * @since 0.0
     */
    public function getKeys($pattern = null)
    {
        $keyPrefix = $this->getKeyPrefix() . Data_Provider::PREFIX_KEY_DELIMETER;

        $size = strlen($keyPrefix);

        $keys = [];

        foreach ($this->getConnection()->getKeys($keyPrefix . $pattern . '*') as $key) {
            $keys[] = substr($key, $size);
        }

        return $keys;
    }
}