<?php
return [
    'time' => '2015-02-12 18:35:46',
    'revision' => '02121835',
    'tableName' => 'bi_blog',
    'dataSourceKey' => 'Ice\\Data\\Source\\Mysqli/default.test',
    'Ice\\Core\\Model' => [
        'blog_pk' => 'blog_pk',
        'blog_name' => 'blog_name',
        'blog_translit' => 'blog_translit',
        'user__fk' => 'user__fk',
        'blog_active' => 'blog_active',
        'blog_created' => 'blog_created',
    ],
    'Ice\\Core\\Model_Scheme' => [
        'columns' => [
            'blog_pk' => [
                'extra' => 'auto_increment',
                'type' => 'bigint(20)',
                'dataType' => 'bigint',
                'length' => '19,0',
                'characterSet' => null,
                'nullable' => false,
                'default' => null,
                'comment' => '',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'blog_name' => [
                'extra' => '',
                'type' => 'varchar(255)',
                'dataType' => 'varchar',
                'length' => '255',
                'characterSet' => 'utf8',
                'nullable' => false,
                'default' => null,
                'comment' => '',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'blog_translit' => [
                'extra' => '',
                'type' => 'varchar(255)',
                'dataType' => 'varchar',
                'length' => '255',
                'characterSet' => 'utf8',
                'nullable' => false,
                'default' => null,
                'comment' => '',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'user__fk' => [
                'extra' => '',
                'type' => 'bigint(20)',
                'dataType' => 'bigint',
                'length' => '19,0',
                'characterSet' => null,
                'nullable' => true,
                'default' => null,
                'comment' => '',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'blog_active' => [
                'extra' => '',
                'type' => 'tinyint(4)',
                'dataType' => 'tinyint',
                'length' => '3,0',
                'characterSet' => null,
                'nullable' => false,
                'default' => '1',
                'comment' => '',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'blog_created' => [
                'extra' => '',
                'type' => 'timestamp',
                'dataType' => 'timestamp',
                'length' => '0',
                'characterSet' => null,
                'nullable' => false,
                'default' => 'CURRENT_TIMESTAMP',
                'comment' => '',
                'is_primary' => false,
                'is_foreign' => false,
            ],
        ],
        'indexes' => [
            'PRIMARY KEY' => [
                'PRIMARY' => [
                    1 => 'blog_pk',
                ],
            ],
            'FOREIGN KEY' => [
                'fk_bi_blog_ice_user' => [
                    'fk_bi_blog_ice_user' => 'user__fk',
                ],
            ],
            'UNIQUE' => [],
        ],
    ],
    'Ice\\Core\\Validator' => [
        'blog_pk' => [
            0 => 'Ice:Not_Null',
        ],
        'blog_name' => [
            0 => 'Ice:Not_Null',
        ],
        'blog_translit' => [
            0 => 'Ice:Not_Null',
        ],
        'user__fk' => [],
        'blog_active' => [
            0 => 'Ice:Not_Null',
        ],
        'blog_created' => [
            0 => 'Ice:Not_Null',
        ],
    ],
    'Ice\\Core\\Form' => [
        'blog_pk' => 'Number',
        'blog_name' => 'Text',
        'blog_translit' => 'Text',
        'user__fk' => 'Number',
        'blog_active' => 'Checkbox',
        'blog_created' => 'Date',
    ],
    'Ice\\Core\\Data' => [
        'blog_pk' => 'text',
        'blog_name' => 'text',
        'blog_translit' => 'text',
        'user__fk' => 'text',
        'blog_active' => 'text',
        'blog_created' => 'text',
    ],
];