<?php
return [
    'time' => '2015-02-12 18:35:46',
    'revision' => '02121835',
    'tableName' => 'bi_comment',
    'dataSourceKey' => 'Ice\\Data\\Source\\Mysqli/default.test',
    'Ice\\Core\\Model' => [
        'comment_pk' => 'comment_pk',
        'comment_title' => 'comment_title',
        'comment_text' => 'comment_text',
        'comment_active' => 'comment_active',
        'comment_created' => 'comment_created',
        'post__fk' => 'post__fk',
    ],
    'Ice\\Core\\Model_Scheme' => [
        'columns' => [
            'comment_pk' => [
                'extra' => 'auto_increment',
                'type' => 'bigint(20)',
                'dataType' => 'bigint',
                'length' => '19,0',
                'characterSet' => null,
                'nullable' => false,
                'default' => null,
                'comment' => '',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'comment_title' => [
                'extra' => '',
                'type' => 'varchar(50)',
                'dataType' => 'varchar',
                'length' => '50',
                'characterSet' => 'utf8',
                'nullable' => false,
                'default' => null,
                'comment' => '',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'comment_text' => [
                'extra' => '',
                'type' => 'text',
                'dataType' => 'text',
                'length' => '65535',
                'characterSet' => 'utf8',
                'nullable' => false,
                'default' => null,
                'comment' => '',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'comment_active' => [
                'extra' => '',
                'type' => 'tinyint(1)',
                'dataType' => 'tinyint',
                'length' => '3,0',
                'characterSet' => null,
                'nullable' => false,
                'default' => '1',
                'comment' => '',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'comment_created' => [
                'extra' => '',
                'type' => 'timestamp',
                'dataType' => 'timestamp',
                'length' => '0',
                'characterSet' => null,
                'nullable' => true,
                'default' => 'CURRENT_TIMESTAMP',
                'comment' => '',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'post__fk' => [
                'extra' => '',
                'type' => 'bigint(20)',
                'dataType' => 'bigint',
                'length' => '19,0',
                'characterSet' => null,
                'nullable' => true,
                'default' => null,
                'comment' => '',
                'is_primary' => false,
                'is_foreign' => false,
            ],
        ],
        'indexes' => [
            'PRIMARY KEY' => [
                'PRIMARY' => [
                    1 => 'comment_pk',
                ],
            ],
            'FOREIGN KEY' => [
                'fk_bi_comment_bi_post' => [
                    'fk_bi_comment_bi_post' => 'post__fk',
                ],
            ],
            'UNIQUE' => [],
        ],
    ],
    'Ice\\Core\\Validator' => [
        'comment_pk' => [
            0 => 'Ice:Not_Null',
        ],
        'comment_title' => [
            0 => 'Ice:Not_Null',
        ],
        'comment_text' => [
            0 => 'Ice:Not_Null',
        ],
        'comment_active' => [
            0 => 'Ice:Not_Null',
        ],
        'comment_created' => [],
        'post__fk' => [],
    ],
    'Ice\\Core\\Form' => [
        'comment_pk' => 'Number',
        'comment_title' => 'Text',
        'comment_text' => 'Textarea',
        'comment_active' => 'Checkbox',
        'comment_created' => 'Date',
        'post__fk' => 'Number',
    ],
    'Ice\\Core\\Data' => [
        'comment_pk' => 'text',
        'comment_title' => 'text',
        'comment_text' => 'text',
        'comment_active' => 'text',
        'comment_created' => 'text',
        'post__fk' => 'text',
    ],
];