<?php
return [
    'time' => '2015-02-13 10:14:26',
    'revision' => '02131014',
    'tableName' => 'bi_post',
    'dataSourceKey' => 'Ice\\Data\\Source\\Mysqli/default.test',
    'fields' => [
        'post_pk' => [
            'Ice\\Core\\Model_Scheme' => [
                'extra' => 'auto_increment',
                'type' => 'bigint(20)',
                'dataType' => 'bigint',
                'length' => '19,0',
                'characterSet' => null,
                'nullable' => false,
                'default' => null,
                'comment' => '',
                'columnName' => 'post_pk',
                'is_primary' => true,
                'is_foreign' => false,
            ],
            'Ice\\Core\\Data' => 'text',
            'Ice\\Core\\Form' => 'Number',
            'Ice\\Core\\Validator' => [],
        ],
        'post_name' => [
            'Ice\\Core\\Model_Scheme' => [
                'extra' => '',
                'type' => 'varchar(255)',
                'dataType' => 'varchar',
                'length' => '255',
                'characterSet' => 'utf8',
                'nullable' => true,
                'default' => null,
                'comment' => '',
                'columnName' => 'post_name',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'Ice\\Core\\Data' => 'text',
            'Ice\\Core\\Form' => 'Text',
            'Ice\\Core\\Validator' => [],
        ],
        'post_translit' => [
            'Ice\\Core\\Model_Scheme' => [
                'extra' => '',
                'type' => 'varchar(255)',
                'dataType' => 'varchar',
                'length' => '255',
                'characterSet' => 'utf8',
                'nullable' => true,
                'default' => null,
                'comment' => '',
                'columnName' => 'post_translit',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'Ice\\Core\\Data' => 'text',
            'Ice\\Core\\Form' => 'Text',
            'Ice\\Core\\Validator' => [],
        ],
        'post_text' => [
            'Ice\\Core\\Model_Scheme' => [
                'extra' => '',
                'type' => 'text',
                'dataType' => 'text',
                'length' => '65535',
                'characterSet' => 'utf8',
                'nullable' => true,
                'default' => null,
                'comment' => '',
                'columnName' => 'post_text',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'Ice\\Core\\Data' => 'text',
            'Ice\\Core\\Form' => 'Textarea',
            'Ice\\Core\\Validator' => [],
        ],
        'post_active' => [
            'Ice\\Core\\Model_Scheme' => [
                'extra' => '',
                'type' => 'tinyint(1)',
                'dataType' => 'tinyint',
                'length' => '3,0',
                'characterSet' => null,
                'nullable' => false,
                'default' => '1',
                'comment' => '',
                'columnName' => 'post_active',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'Ice\\Core\\Data' => 'text',
            'Ice\\Core\\Form' => 'Checkbox',
            'Ice\\Core\\Validator' => [
                0 => 'Ice:Not_Null',
            ],
        ],
        'post_created' => [
            'Ice\\Core\\Model_Scheme' => [
                'extra' => '',
                'type' => 'timestamp',
                'dataType' => 'timestamp',
                'length' => '0',
                'characterSet' => null,
                'nullable' => true,
                'default' => null,
                'comment' => '',
                'columnName' => 'post_created',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'Ice\\Core\\Data' => 'text',
            'Ice\\Core\\Form' => 'Date',
            'Ice\\Core\\Validator' => [],
        ],
        'blog__fk' => [
            'Ice\\Core\\Model_Scheme' => [
                'extra' => '',
                'type' => 'bigint(20)',
                'dataType' => 'bigint',
                'length' => '19,0',
                'characterSet' => null,
                'nullable' => true,
                'default' => null,
                'comment' => '',
                'columnName' => 'blog__fk',
                'is_primary' => false,
                'is_foreign' => true,
            ],
            'Ice\\Core\\Data' => 'text',
            'Ice\\Core\\Form' => 'Number',
            'Ice\\Core\\Validator' => [],
        ],
    ],
    'indexes' => [
        'PRIMARY KEY' => [
            'PRIMARY' => [
                1 => 'post_pk',
            ],
        ],
        'FOREIGN KEY' => [
            'fk_bi_post_bi_blog' => [
                'fk_bi_post_bi_blog' => 'blog__fk',
            ],
        ],
        'UNIQUE' => [],
    ],
];