<?php
return [
    'time' => '2015-02-15 20:57:42',
    'revision' => '02152057',
    'tableName' => 'ice_account',
    'dataSourceKey' => 'Ice\\Data\\Source\\Mysqli/default.test',
    'fields' => [
        'account_pk' => [
            'Ice\\Core\\Model_Scheme' => [
                'extra' => 'auto_increment',
                'type' => 'bigint(20)',
                'dataType' => 'bigint',
                'length' => '19,0',
                'characterSet' => null,
                'nullable' => false,
                'default' => null,
                'comment' => '',
                'columnName' => 'account_pk',
                'is_primary' => true,
                'is_foreign' => false,
            ],
            'Ice\\Core\\Data' => 'text',
            'Ice\\Core\\Form' => 'Number',
            'Ice\\Core\\Validator' => [],
        ],
        'user__fk' => [
            'Ice\\Core\\Model_Scheme' => [
                'extra' => '',
                'type' => 'bigint(20)',
                'dataType' => 'bigint',
                'length' => '19,0',
                'characterSet' => null,
                'nullable' => true,
                'default' => null,
                'comment' => '',
                'columnName' => 'user__fk',
                'is_primary' => false,
                'is_foreign' => true,
            ],
            'Ice\\Core\\Data' => 'text',
            'Ice\\Core\\Form' => 'Number',
            'Ice\\Core\\Validator' => [],
        ],
        'login' => [
            'Ice\\Core\\Model_Scheme' => [
                'extra' => '',
                'type' => 'varchar(255)',
                'dataType' => 'varchar',
                'length' => '255',
                'characterSet' => 'utf8',
                'nullable' => true,
                'default' => null,
                'comment' => '',
                'columnName' => 'login',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'Ice\\Core\\Data' => 'text',
            'Ice\\Core\\Form' => 'Text',
            'Ice\\Core\\Validator' => [],
        ],
        'password' => [
            'Ice\\Core\\Model_Scheme' => [
                'extra' => '',
                'type' => 'varchar(255)',
                'dataType' => 'varchar',
                'length' => '255',
                'characterSet' => 'utf8',
                'nullable' => true,
                'default' => null,
                'comment' => '',
                'columnName' => 'password',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'Ice\\Core\\Data' => 'text',
            'Ice\\Core\\Form' => 'Text',
            'Ice\\Core\\Validator' => [],
        ],
        'account_active' => [
            'Ice\\Core\\Model_Scheme' => [
                'extra' => '',
                'type' => 'tinyint(4)',
                'dataType' => 'tinyint',
                'length' => '3,0',
                'characterSet' => null,
                'nullable' => false,
                'default' => '1',
                'comment' => '',
                'columnName' => 'account_active',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'Ice\\Core\\Data' => 'text',
            'Ice\\Core\\Form' => 'Checkbox',
            'Ice\\Core\\Validator' => [
                0 => 'Ice:Not_Null',
            ],
        ],
    ],
    'indexes' => [
        'PRIMARY KEY' => [
            'PRIMARY' => [
                1 => 'account_pk',
            ],
        ],
        'FOREIGN KEY' => [
            'fk_ice_account_ice_user' => [
                'fk_ice_account_ice_user' => 'user__fk',
            ],
        ],
        'UNIQUE' => [],
    ],
];