<?php
return [
    'time' => '2015-02-12 18:35:46',
    'revision' => '02121835',
    'tableName' => 'ice_user',
    'dataSourceKey' => 'Ice\\Data\\Source\\Mysqli/default.test',
    'Ice\\Core\\Model' => [
        'user_pk' => 'user_pk',
        'user_phone' => 'user_phone',
        'user_email' => 'user_email',
        'user_name' => 'user_name',
        'surname' => 'surname',
        'patronymic' => 'patronymic',
        'user_active' => 'user_active',
        'user_created' => 'user_created',
    ],
    'Ice\\Core\\Model_Scheme' => [
        'columns' => [
            'user_pk' => [
                'extra' => 'auto_increment',
                'type' => 'bigint(20)',
                'dataType' => 'bigint',
                'length' => '19,0',
                'characterSet' => null,
                'nullable' => false,
                'default' => null,
                'comment' => '',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'user_phone' => [
                'extra' => '',
                'type' => 'varchar(11)',
                'dataType' => 'varchar',
                'length' => '11',
                'characterSet' => 'utf8',
                'nullable' => true,
                'default' => null,
                'comment' => '',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'user_email' => [
                'extra' => '',
                'type' => 'varchar(255)',
                'dataType' => 'varchar',
                'length' => '255',
                'characterSet' => 'utf8',
                'nullable' => true,
                'default' => null,
                'comment' => '',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'user_name' => [
                'extra' => '',
                'type' => 'varchar(255)',
                'dataType' => 'varchar',
                'length' => '255',
                'characterSet' => 'utf8',
                'nullable' => true,
                'default' => null,
                'comment' => '',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'surname' => [
                'extra' => '',
                'type' => 'varchar(255)',
                'dataType' => 'varchar',
                'length' => '255',
                'characterSet' => 'utf8',
                'nullable' => true,
                'default' => null,
                'comment' => '',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'patronymic' => [
                'extra' => '',
                'type' => 'varchar(255)',
                'dataType' => 'varchar',
                'length' => '255',
                'characterSet' => 'utf8',
                'nullable' => true,
                'default' => null,
                'comment' => '',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'user_active' => [
                'extra' => '',
                'type' => 'tinyint(4)',
                'dataType' => 'tinyint',
                'length' => '3,0',
                'characterSet' => null,
                'nullable' => false,
                'default' => '1',
                'comment' => '',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'user_created' => [
                'extra' => '',
                'type' => 'timestamp',
                'dataType' => 'timestamp',
                'length' => '0',
                'characterSet' => null,
                'nullable' => true,
                'default' => null,
                'comment' => '',
                'is_primary' => false,
                'is_foreign' => false,
            ],
        ],
        'indexes' => [
            'PRIMARY KEY' => [
                'PRIMARY' => [
                    1 => 'user_pk',
                ],
            ],
            'FOREIGN KEY' => [],
            'UNIQUE' => [],
        ],
    ],
    'Ice\\Core\\Validator' => [
        'user_pk' => [
            0 => 'Ice:Not_Null',
        ],
        'user_phone' => [],
        'user_email' => [],
        'user_name' => [],
        'surname' => [],
        'patronymic' => [],
        'user_active' => [
            0 => 'Ice:Not_Null',
        ],
        'user_created' => [],
    ],
    'Ice\\Core\\Form' => [
        'user_pk' => 'Number',
        'user_phone' => 'Text',
        'user_email' => 'Text',
        'user_name' => 'Text',
        'surname' => 'Text',
        'patronymic' => 'Text',
        'user_active' => 'Checkbox',
        'user_created' => 'Date',
    ],
    'Ice\\Core\\Data' => [
        'user_pk' => 'text',
        'user_phone' => 'text',
        'user_email' => 'text',
        'user_name' => 'text',
        'surname' => 'text',
        'patronymic' => 'text',
        'user_active' => 'text',
        'user_created' => 'text',
    ],
];