<?php
return [
    'time' => '2015-02-13 10:14:26',
    'revision' => '02131014',
    'tableName' => 'ice_user',
    'dataSourceKey' => 'Ice\\Data\\Source\\Mysqli/default.test',
    'fields' => [
        'user_pk' => [
            'Ice\\Core\\Model_Scheme' => [
                'extra' => 'auto_increment',
                'type' => 'bigint(20)',
                'dataType' => 'bigint',
                'length' => '19,0',
                'characterSet' => null,
                'nullable' => false,
                'default' => null,
                'comment' => '',
                'columnName' => 'user_pk',
                'is_primary' => true,
                'is_foreign' => false,
            ],
            'Ice\\Core\\Data' => 'text',
            'Ice\\Core\\Form' => 'Number',
            'Ice\\Core\\Validator' => [],
        ],
        'user_phone' => [
            'Ice\\Core\\Model_Scheme' => [
                'extra' => '',
                'type' => 'varchar(11)',
                'dataType' => 'varchar',
                'length' => '11',
                'characterSet' => 'utf8',
                'nullable' => true,
                'default' => null,
                'comment' => '',
                'columnName' => 'user_phone',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'Ice\\Core\\Data' => 'text',
            'Ice\\Core\\Form' => 'Text',
            'Ice\\Core\\Validator' => [],
        ],
        'user_email' => [
            'Ice\\Core\\Model_Scheme' => [
                'extra' => '',
                'type' => 'varchar(255)',
                'dataType' => 'varchar',
                'length' => '255',
                'characterSet' => 'utf8',
                'nullable' => true,
                'default' => null,
                'comment' => '',
                'columnName' => 'user_email',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'Ice\\Core\\Data' => 'text',
            'Ice\\Core\\Form' => 'Text',
            'Ice\\Core\\Validator' => [],
        ],
        'user_name' => [
            'Ice\\Core\\Model_Scheme' => [
                'extra' => '',
                'type' => 'varchar(255)',
                'dataType' => 'varchar',
                'length' => '255',
                'characterSet' => 'utf8',
                'nullable' => true,
                'default' => null,
                'comment' => '',
                'columnName' => 'user_name',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'Ice\\Core\\Data' => 'text',
            'Ice\\Core\\Form' => 'Text',
            'Ice\\Core\\Validator' => [],
        ],
        'surname' => [
            'Ice\\Core\\Model_Scheme' => [
                'extra' => '',
                'type' => 'varchar(255)',
                'dataType' => 'varchar',
                'length' => '255',
                'characterSet' => 'utf8',
                'nullable' => true,
                'default' => null,
                'comment' => '',
                'columnName' => 'surname',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'Ice\\Core\\Data' => 'text',
            'Ice\\Core\\Form' => 'Text',
            'Ice\\Core\\Validator' => [],
        ],
        'patronymic' => [
            'Ice\\Core\\Model_Scheme' => [
                'extra' => '',
                'type' => 'varchar(255)',
                'dataType' => 'varchar',
                'length' => '255',
                'characterSet' => 'utf8',
                'nullable' => true,
                'default' => null,
                'comment' => '',
                'columnName' => 'patronymic',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'Ice\\Core\\Data' => 'text',
            'Ice\\Core\\Form' => 'Text',
            'Ice\\Core\\Validator' => [],
        ],
        'user_active' => [
            'Ice\\Core\\Model_Scheme' => [
                'extra' => '',
                'type' => 'tinyint(4)',
                'dataType' => 'tinyint',
                'length' => '3,0',
                'characterSet' => null,
                'nullable' => false,
                'default' => '1',
                'comment' => '',
                'columnName' => 'user_active',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'Ice\\Core\\Data' => 'text',
            'Ice\\Core\\Form' => 'Checkbox',
            'Ice\\Core\\Validator' => [
                0 => 'Ice:Not_Null',
            ],
        ],
        'user_created' => [
            'Ice\\Core\\Model_Scheme' => [
                'extra' => '',
                'type' => 'timestamp',
                'dataType' => 'timestamp',
                'length' => '0',
                'characterSet' => null,
                'nullable' => true,
                'default' => null,
                'comment' => '',
                'columnName' => 'user_created',
                'is_primary' => false,
                'is_foreign' => false,
            ],
            'Ice\\Core\\Data' => 'text',
            'Ice\\Core\\Form' => 'Date',
            'Ice\\Core\\Validator' => [],
        ],
    ],
    'indexes' => [
        'PRIMARY KEY' => [
            'PRIMARY' => [
                1 => 'user_pk',
            ],
        ],
        'FOREIGN KEY' => [],
        'UNIQUE' => [],
    ],
];