imports:
    - php

filter:
#    paths:
#        - source/*
    excluded_paths:
        - bin/*
        - config/*
        - resource/*
        - tests/*
        - var/*
        - public/*
tools:
    external_code_coverage:
        timeout: 2100 # Timeout in seconds.

    php_sim: false
    php_cpd: false
