#!/usr/bin/env php
<?php
/**
 * @file Console script
 *
 * Run and flush ice application via console
 * @author dp <denis.a.shestakov@gmail.com>
 *
 * @version 0.0
 * @since 0.0
 */

require_once __DIR__ . '/app.php';