<?php
return [
    'Application failure' => [
        'en' => 'Application failure',
        'be' => 'Збой прыкладанні',
        'ca' => 'Aplicació fracàs',
        'cs' => 'Selhání aplikace',
        'da' => 'Anvendelse fiasko',
        'de' => 'Anwendungsfehler',
        'el' => 'Εφαρμογή αποτυχία',
        'es' => 'El fallo de la aplicación',
        'et' => 'Taotluse jätmine',
        'fi' => 'Hakemuksen jättäminen',
        'fr' => 'L\'échec de l\'Application',
        'hu' => 'Alkalmazás hiba',
        'it' => 'La mancata applicazione',
        'lt' => 'Taikymo nesėkmė',
        'lv' => 'Pieteikumu neveiksmes',
        'mk' => 'Апликацијата неуспех',
        'nl' => 'Toepassingsfout',
        'no' => 'Apparatfeil',
        'pt' => 'Falha de aplicativo',
        'ru' => 'Сбой приложения',
        'sk' => 'Aplikácia zlyhanie',
        'sl' => 'Prijave okvare',
        'sq' => 'Aplikimi dështimit',
        'sv' => 'Misslyckande',
        'tr' => 'Uygulama hatası',
        'uk' => 'Збій програми',
    ],
    'Implement {$0} for {$1}' => [
        'en' => 'Implement {$0} for {$1}',
        'ru' => 'Реализовать {$0} для {$1}',
    ],
];