<?php
return [
    'Updating scheme ({$0})' => [
        'en' => 'Updating scheme ({$0})',
        'be' => 'Абнаўленне схемы ({$0})',
        'ca' => 'Actualització de l\'esquema de ({$0})',
        'cs' => 'Aktualizace systému ({$0})',
        'da' => 'Opdatering af ordningen ({$0})',
        'de' => 'Aktualisierung Regelung ({$0})',
        'el' => 'Ενημέρωση καθεστώς ({$0})',
        'es' => 'La actualización de esquema ({$0})',
        'et' => 'Ajakohastamise kava ({$0})',
        'fi' => 'Päivittämällä ohjelman ({$0})',
        'fr' => 'La mise à jour de schéma ({$0})',
        'hu' => 'Frissítési rendszer ({$0})',
        'it' => 'Aggiornamento del sistema ({$0})',
        'lt' => 'Atnaujinimo sistema ({$0})',
        'lv' => 'Atjauninot sistēmu ({$0})',
        'mk' => 'Ажурирање шема ({$0})',
        'nl' => 'Het bijwerken van de regeling ({$0})',
        'no' => 'Oppdatering av ordningen ({$0})',
        'pt' => 'Atualização de esquema ({$0})',
        'ru' => 'Обновление схемы ({$0})',
        'sk' => 'Aktualizácia systému ({$0})',
        'sl' => 'Posodobitev sheme ({$0})',
        'sq' => 'Përditësimi i skemës ({$0})',
        'sv' => 'Uppdatera systemet ({$0})',
        'tr' => 'Düzeni ({$0})güncelleme ',
        'uk' => 'Оновлення схеми ({$0})',
    ],
];