<?php
return [
    'time' => '2014-12-28 14:37:33',
    'revision' => '12281437',
    'scheme' => 'test',
    'modelClass' => 'Ice\\Model\\Account',
    'prefix' => 'ice',
    'columns' => [
        'account_pk' => [
            'extra' => 'auto_increment',
            'type' => 'bigint(20)',
            'dataType' => 'bigint',
            'length' => '19,0',
            'characterSet' => null,
            'nullable' => false,
            'default' => null,
            'comment' => '',
            'is_primary' => true,
            'is_foreign' => false,
        ],
        'user__fk' => [
            'extra' => '',
            'type' => 'bigint(20)',
            'dataType' => 'bigint',
            'length' => '19,0',
            'characterSet' => null,
            'nullable' => true,
            'default' => null,
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => true,
        ],
        'login' => [
            'extra' => '',
            'type' => 'varchar(255)',
            'dataType' => 'varchar',
            'length' => '255',
            'characterSet' => 'utf8',
            'nullable' => true,
            'default' => null,
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => false,
        ],
        'password' => [
            'extra' => '',
            'type' => 'varchar(255)',
            'dataType' => 'varchar',
            'length' => '255',
            'characterSet' => 'utf8',
            'nullable' => true,
            'default' => null,
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => false,
        ],
        'account_active' => [
            'extra' => '',
            'type' => 'tinyint(4)',
            'dataType' => 'tinyint',
            'length' => '3,0',
            'characterSet' => null,
            'nullable' => false,
            'default' => '1',
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => false,
        ],
    ],
    'indexes' => [
        'PRIMARY KEY' => [
            'PRIMARY' => [
                1 => 'account_pk',
            ],
        ],
        'FOREIGN KEY' => [
            'fk_ice_account_ice_user' => [
                'fk_ice_account_ice_user' => 'user__fk',
            ],
        ],
        'UNIQUE' => [],
    ],
];