<?php
return [
    'time' => '2015-01-08 12:16:16',
    'revision' => '01081216',
    'scheme' => 'test',
    'modelClass' => 'Ice\\Model\\Test',
    'prefix' => 'ice',
    'columns' => [
        'id' => [
            'extra' => 'auto_increment',
            'type' => 'bigint(20)',
            'dataType' => 'bigint',
            'length' => '19,0',
            'characterSet' => null,
            'nullable' => false,
            'default' => null,
            'comment' => '',
            'is_primary' => true,
            'is_foreign' => false,
        ],
        'test_name' => [
            'extra' => '',
            'type' => 'varchar(50)',
            'dataType' => 'varchar',
            'length' => '50',
            'characterSet' => 'utf8',
            'nullable' => true,
            'default' => null,
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => false,
        ],
        'name2' => [
            'extra' => '',
            'type' => 'varchar(50)',
            'dataType' => 'varchar',
            'length' => '50',
            'characterSet' => 'utf8',
            'nullable' => false,
            'default' => null,
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => false,
        ],
    ],
    'indexes' => [
        'PRIMARY KEY' => [
            'PRIMARY' => [
                1 => 'id',
            ],
        ],
        'FOREIGN KEY' => [],
        'UNIQUE' => [],
    ],
];