<?php
return [
    'time' => '2014-12-28 14:37:33',
    'revision' => '12281437',
    'scheme' => 'test',
    'modelClass' => 'Ice\\Model\\User',
    'prefix' => 'ice',
    'columns' => [
        'user_pk' => [
            'extra' => 'auto_increment',
            'type' => 'bigint(20)',
            'dataType' => 'bigint',
            'length' => '19,0',
            'characterSet' => null,
            'nullable' => false,
            'default' => null,
            'comment' => '',
            'is_primary' => true,
            'is_foreign' => false,
        ],
        'user_phone' => [
            'extra' => '',
            'type' => 'varchar(11)',
            'dataType' => 'varchar',
            'length' => '11',
            'characterSet' => 'utf8',
            'nullable' => true,
            'default' => null,
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => false,
        ],
        'user_email' => [
            'extra' => '',
            'type' => 'varchar(255)',
            'dataType' => 'varchar',
            'length' => '255',
            'characterSet' => 'utf8',
            'nullable' => true,
            'default' => null,
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => false,
        ],
        'user_name' => [
            'extra' => '',
            'type' => 'varchar(255)',
            'dataType' => 'varchar',
            'length' => '255',
            'characterSet' => 'utf8',
            'nullable' => true,
            'default' => null,
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => false,
        ],
        'surname' => [
            'extra' => '',
            'type' => 'varchar(255)',
            'dataType' => 'varchar',
            'length' => '255',
            'characterSet' => 'utf8',
            'nullable' => true,
            'default' => null,
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => false,
        ],
        'patronymic' => [
            'extra' => '',
            'type' => 'varchar(255)',
            'dataType' => 'varchar',
            'length' => '255',
            'characterSet' => 'utf8',
            'nullable' => true,
            'default' => null,
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => false,
        ],
        'user_active' => [
            'extra' => '',
            'type' => 'tinyint(4)',
            'dataType' => 'tinyint',
            'length' => '3,0',
            'characterSet' => null,
            'nullable' => false,
            'default' => '1',
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => false,
        ],
        'user_created' => [
            'extra' => '',
            'type' => 'timestamp',
            'dataType' => 'timestamp',
            'length' => '0',
            'characterSet' => null,
            'nullable' => true,
            'default' => 'CURRENT_TIMESTAMP',
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => false,
        ],
    ],
    'indexes' => [
        'PRIMARY KEY' => [
            'PRIMARY' => [
                1 => 'user_pk',
            ],
        ],
        'FOREIGN KEY' => [],
        'UNIQUE' => [],
    ],
];