<?php

namespace Ice\Bootstrap;

use Composer\Autoload\ClassLoader;
use Ice\Core\Bootstrap;

class Ice extends Bootstrap
{
    public function init(ClassLoader $loader, $force = false)
    {
        define('MODULE_CONFIG_PATH', $this->getModuleConfigPath());

        parent::init($loader, $force); // TODO: Change the autogenerated stub
    }

    protected static function getDefaultKey()
    {
        return 'Config/Ice/Core/Module.php';
    }
}