<?php
return [
    'Application failed' => [
        'en' => 'Application failed',
        'be' => 'Прыкладанне не ўдалося',
        'ca' => 'Aplicació ha fallat',
        'cs' => 'Aplikace se nezdařilo',
        'da' => 'Ansøgningen ikke',
        'de' => 'Anwendung fehlgeschlagen',
        'el' => 'Η εφαρμογή απέτυχε',
        'es' => 'Aplicación no se ha podido',
        'et' => 'Application failed',
        'fi' => 'Sovellus epäonnistui',
        'fr' => 'L\'Application a échoué',
        'hu' => 'Az alkalmazás nem',
        'it' => 'Applicazione non',
        'lt' => 'Prašymas nepavyko',
        'lv' => 'Pieteikums nav',
        'mk' => 'Апликација не успеа',
        'nl' => 'Toepassing niet',
        'no' => 'Programmet mislyktes',
        'pt' => 'Aplicação falhou',
        'ru' => 'Приложение не удалось',
        'sk' => 'Aplikácia sa nepodarilo',
        'sl' => 'Aplikacija se ni uspela',
        'sq' => 'Aplikim ka dështuar',
        'sv' => 'Ansökan kunde inte',
        'tr' => 'Uygulama başarısız',
        'uk' => 'Додаток не вдалося',
    ],
];