<?php
return [
    'Could not found required param {$0}' => [
        'en' => 'Could not found required param {$0}',
        'be' => 'Не змаглі знайсці неабходныя param {$0}',
        'ca' => 'No podia trobar necessaris param {$0}',
        'cs' => 'Nemohl nalézt požadované param {$0}',
        'da' => 'Kunne ikke fundet påkrævet param {$0}',
        'de' => 'Konnte nicht gefunden erforderlich param {$0}',
        'el' => 'Δεν θα μπορούσε να βρεθεί απαιτείται param {$0}',
        'es' => 'No se pudo encontrar requiere param {$0}',
        'et' => 'Ei suutnud leida vajalik param {$0}',
        'fi' => 'Voi ei löydy vaaditaan param {$0}',
        'fr' => 'Ne pouvait pas trouver nécessaire de param {$0}',
        'hu' => 'Lehet nem található szükséges param {$0}',
        'it' => 'Non poteva trovato richiesto param {$0}',
        'lt' => 'Nepavyko rasti reikalingų param {$0}',
        'lv' => 'Nevarēja atrast nepieciešamo param {$0}',
        'mk' => 'Не можеше да најде потребни param {$0}',
        'nl' => 'Kon niet gevonden vereist param {$0}',
        'no' => 'Kunne ikke funnet nødvendig param {$0}',
        'pt' => 'Não foi encontrado necessário param {$0}',
        'ru' => 'Не смогли найти необходимые param {$0}',
        'sk' => 'Nenašli požadované param {$0}',
        'sl' => 'Ni mogel najti potrebne param {$0}',
        'sq' => 'Nuk mund të gjendet kërkohet param {$0}',
        'sv' => 'Kunde inte hittas krävs param {$0}',
        'tr' => 'Gerekli param {$0}bulunamadı ',
        'uk' => 'Не змогли знайти необхідні param {$0}',
    ],
];