<?php
return [
    'test' => [
        'en' => 'test',
        'be' => 'тэст',
        'ca' => 'prova',
        'cs' => 'test',
        'da' => 'test',
        'de' => 'test',
        'el' => 'δοκιμή',
        'es' => 'de prueba',
        'et' => 'katse',
        'fi' => 'testi',
        'fr' => 'test',
        'hu' => 'teszt',
        'it' => 'prova',
        'lt' => 'testas',
        'lv' => 'tests',
        'mk' => 'тест',
        'nl' => 'test',
        'no' => 'test',
        'pt' => 'teste',
        'ru' => 'тест',
        'sk' => 'test',
        'sl' => 'test',
        'sq' => 'test',
        'sv' => 'test',
        'tr' => 'test',
        'uk' => 'тест',
    ],
];