<?php
return [
    'time' => '2015-01-28 13:20:41',
    'revision' => '01281320',
    'scheme' => 'test',
    'modelClass' => 'Ice\\Model\\Bi_Comment',
    'prefix' => '',
    'columns' => [
        'comment_pk' => [
            'extra' => 'auto_increment',
            'type' => 'bigint(20)',
            'dataType' => 'bigint',
            'length' => '19,0',
            'characterSet' => null,
            'nullable' => false,
            'default' => null,
            'comment' => '',
            'is_primary' => true,
            'is_foreign' => false,
        ],
        'comment_title' => [
            'extra' => '',
            'type' => 'varchar(50)',
            'dataType' => 'varchar',
            'length' => '50',
            'characterSet' => 'utf8',
            'nullable' => false,
            'default' => null,
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => false,
        ],
        'comment_text' => [
            'extra' => '',
            'type' => 'text',
            'dataType' => 'text',
            'length' => '65535',
            'characterSet' => 'utf8',
            'nullable' => false,
            'default' => null,
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => false,
        ],
        'comment_active' => [
            'extra' => '',
            'type' => 'tinyint(1)',
            'dataType' => 'tinyint',
            'length' => '3,0',
            'characterSet' => null,
            'nullable' => false,
            'default' => '1',
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => false,
        ],
        'comment_created' => [
            'extra' => '',
            'type' => 'timestamp',
            'dataType' => 'timestamp',
            'length' => '0',
            'characterSet' => null,
            'nullable' => true,
            'default' => 'CURRENT_TIMESTAMP',
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => false,
        ],
        'post__fk' => [
            'extra' => '',
            'type' => 'bigint(20)',
            'dataType' => 'bigint',
            'length' => '19,0',
            'characterSet' => null,
            'nullable' => true,
            'default' => null,
            'comment' => '',
            'is_primary' => false,
            'is_foreign' => true,
        ],
    ],
    'indexes' => [
        'PRIMARY KEY' => [
            'PRIMARY' => [
                1 => 'comment_pk',
            ],
        ],
        'FOREIGN KEY' => [
            'fk_bi_comment_bi_post' => [
                'fk_bi_comment_bi_post' => 'post__fk',
            ],
        ],
        'UNIQUE' => [],
    ],
];