<?php
return [
    'Could not found required param {$0} for class {$1}' => [
        'ru' => 'Could not found required param {$0} for class {$1}',
    ],
    'Config for {$0} not found' => [
        'en' => 'Config for {$0} not found',
        'be' => 'Config {$0} не знойдзены',
        'ca' => 'De configuració per {$0} no s\'ha trobat',
        'cs' => 'Config pro {$0} nebyl nalezen',
        'da' => 'Config til {$0} blev ikke fundet',
        'de' => 'Config {$0} nicht gefunden',
        'el' => 'Config για {$0} δεν βρέθηκε',
        'es' => 'Config {$0} no se encuentra',
        'et' => 'Config {$0} ei leitud',
        'fi' => 'Config {$0} ei löydy',
        'fr' => 'Config pour {$0} introuvable',
        'hu' => 'Config {$0} nem található',
        'it' => 'Config {$0} non trovato',
        'lt' => 'Config {$0} nerastas',
        'lv' => 'Config {$0} nav atrasts',
        'mk' => 'Config за {$0} не е пронајдена',
        'nl' => 'Config {$0} is niet gevonden',
        'no' => 'Config for {$0} finnes ikke',
        'pt' => 'Config para {$0} não encontrado',
        'ru' => 'Config {$0} не найден',
        'sk' => 'Config na {$0} nenašiel',
        'sl' => 'Config za {$0} ni mogoče najti',
        'sq' => 'Config për {$0} nuk u gjet',
        'sv' => 'Config för {$0} hittades inte',
        'tr' => 'İçin {$0} bulunamadı Config ',
        'uk' => 'Config {$0} не знайдено',
    ],
];