<?php
return [
    'In environment config param {$0} not found' => [
        'ru' => 'В конфиге окружений параметр <b>{$0}</b> не найден',
        'en' => 'In environment config param {$0} not found',
    ],
    'Data source driver [{$0}]: ' => [
        'en' => 'Data source driver [{$0}]: ',
        'be' => 'Крыніца дадзеных драйвер [{$0}]: ',
        'ca' => 'La font de dades del conductor [{$0}]: ',
        'cs' => 'Data source ovladač [{$0}]: ',
        'da' => 'Data source driver [{$0}]: ',
        'de' => 'Daten-source-Treiber [{$0}]: ',
        'el' => 'Πηγή των δεδομένων του προγράμματος οδήγησης [{$0}]: ',
        'es' => 'Controlador de origen de datos [{$0}]: ',
        'et' => 'Andmete allikas juht [{$0}]: ',
        'fi' => 'Tietolähde ohjain [{$0}]: ',
        'fr' => 'Pilote de source de données [{$0}]: ',
        'hu' => 'Adatok forrása illesztőprogram [{$0}]: ',
        'it' => 'Driver di origine dati [{$0}]: ',
        'lt' => 'Duomenų šaltinis vairuotojas [{$0}]: ',
        'lv' => 'Datu avots vadītāja [{$0}]: ',
        'mk' => 'Извор на податоци возачот [{$0}]: ',
        'nl' => 'Data source driver [{$0}]: ',
        'no' => 'Datakilde driver [{$0}]: ',
        'pt' => 'Driver de fonte de dados [{$0}]: ',
        'ru' => 'Источник данных драйвер [{$0}]: ',
        'sk' => 'Data source ovládač [{$0}]: ',
        'sl' => 'Vir podatkov voznik [{$0}]: ',
        'sq' => 'Burimi i të dhënave shofer [{$0}]: ',
        'sv' => 'Datakälla förare [{$0}]: ',
        'tr' => 'Veri kaynağı sürücüsü [{$0}]: ',
        'uk' => 'Джерело даних драйвер [{$0}]: ',
    ],
];