<?php
return [
    'File {$0} exists, but class {$1} not found' => [
        'ru' => 'File {$0} exists, but class {$1} not found',
    ],
    'Sql query is empty' => [
        'ru' => 'Sql query is empty',
    ],
    'Invalid command line. Usage: ./cli Action_Call param=value' => [
        'en' => 'Invalid command line. Usage: ./cli Action_Call param=value',
    ],
    'Не удалось забиндить параметры' => [
        'en' => 'Не удалось забиндить параметры',
    ],
    'Unknown data source query statment type ""' => [
        'en' => 'Unknown data source query statment type ""',
    ],
    'Primary key is empty' => [
        'en' => 'Primary key is empty',
    ],
    'Implement flushAll() method.' => [
        'ru' => 'Implement flushAll() method.',
    ],
    'Could not set value:
. Field "" not found in Model "Upload_Task"' => [
        'ru' => 'Could not set value:
. Field "" not found in Model "Upload_Task"',
    ],
    'Implement set() method.' => [
        'en' => 'Implement set() method.',
    ],
    'Could not set value:
. Field "" not found in Model "Test"' => [
        'en' => 'Could not set value:
. Field "" not found in Model "Test"',
    ],
    'Query is empty' => [
        'en' => 'Query is empty',
    ],
    'Not implemented' => [
        'en' => 'Not implemented',
    ],
    'Data_Scheme_Error - Array' => [
        'en' => 'Data_Scheme_Error - Array',
        'be' => 'Data_Scheme_Error - Масіў',
        'ca' => 'Data_Scheme_Error - Matriu De',
        'cs' => 'Data_Scheme_Error - Pole',
        'da' => 'Data_Scheme_Error - Array',
        'de' => 'Data_Scheme_Error - Array',
        'el' => 'Data_Scheme_Error - Πίνακα',
        'es' => 'Data_Scheme_Error - Matriz',
        'et' => 'Data_Scheme_Error - Massiivi',
        'fi' => 'Data_Scheme_Error - Array',
        'fr' => 'Data_Scheme_Error - Tableau',
        'hu' => 'Data_Scheme_Error - Tömb',
        'it' => 'Data_Scheme_Error - Array',
        'lt' => 'Data_Scheme_Error - Matrica',
        'lv' => 'Data_Scheme_Error - Masīvs',
        'mk' => 'Data_Scheme_Error - Низа',
        'nl' => 'Data_Scheme_Error - Array',
        'no' => 'Data_Scheme_Error - Array',
        'pt' => 'Data_Scheme_Error - Matriz',
        'ru' => 'Data_Scheme_Error - Массив',
        'sk' => 'Data_Scheme_Error - Pole',
        'sl' => 'Data_Scheme_Error - Matrične',
        'sq' => 'Data_Scheme_Error - Grup',
        'sv' => 'Data_Scheme_Error - Array',
        'tr' => 'Data_Scheme_Error - Dizi',
        'uk' => 'Data_Scheme_Error - Масив',
    ],
    'File_Not_Found - Array' => [
        'en' => 'File_Not_Found - Array',
        'be' => 'Filename - Масіў',
        'ca' => 'File_Not_Found - Matriu De',
        'cs' => 'File_Not_Found - Pole',
        'da' => 'File_Not_Found - Array',
        'de' => 'File_Not_Found - Array',
        'el' => 'File_Not_Found - Πίνακα',
        'es' => 'File_Not_Found - Matriz',
        'et' => 'File_Not_Found - Massiivi',
        'fi' => 'File_Not_Found - Array',
        'fr' => 'File_Not_Found - Tableau',
        'hu' => 'File_Not_Found - Tömb',
        'it' => 'File_Not_Found - Array',
        'lt' => 'File_Not_Found - Matrica',
        'lv' => 'File_Not_Found - Masīvs',
        'mk' => 'File_Not_Found - Низа',
        'nl' => 'File_Not_Found - Array',
        'no' => 'File_Not_Found - Array',
        'pt' => 'File_Not_Found - Matriz',
        'ru' => 'Filename - Массив',
        'sk' => 'File_Not_Found - Pole',
        'sl' => 'File_Not_Found - Matrične',
        'sq' => 'File_Not_Found - Grup',
        'sv' => 'File_Not_Found - Array',
        'tr' => 'File_Not_Found - Dizi',
        'uk' => 'Filename - Масив',
    ],
    'Error - Array' => [
        'en' => 'Error - Array',
        'be' => 'Памылка - Масіў',
        'ca' => 'Error - Matriu De',
        'cs' => 'Chyba - Pole',
        'da' => 'Fejl - Array',
        'de' => 'Fehler - Array',
        'el' => 'Σφάλμα - Πίνακα',
        'es' => 'Error - Matriz',
        'et' => 'Viga - Massiivi',
        'fi' => 'Virhe - Array',
        'fr' => 'Erreur - Tableau',
        'hu' => 'Hiba - Tömb',
        'it' => 'Errore Di Matrice',
        'lt' => 'Klaida - Matrica',
        'lv' => 'Kļūda - Masīvs',
        'mk' => 'Грешка - Низа',
        'nl' => 'Fout - Array',
        'no' => 'Feil - Array',
        'pt' => 'Erro - Matriz',
        'ru' => 'Ошибка - Массив',
        'sk' => 'Chyba - Pole',
        'sl' => 'Napaka - Matrične',
        'sq' => 'Gabim - Grup',
        'sv' => 'Fel - Array',
        'tr' => 'Hata - Dizi',
        'uk' => 'Помилка - Масив',
    ],
    'route for url \'{$0}\' not found' => [
        'en' => 'route for url \'{$0}\' not found',
        'be' => 'маршрут для url-адрас \'{$0}\' не знойдзены',
        'ca' => 'ruta de la url \'{$0}\' no trobat',
        'cs' => 'trasy pro url, \'{$0}\' nebyl nalezen',
        'da' => 'ruten for url \'{$0}\' blev ikke fundet',
        'de' => 'route für url \'{$0}\' wurde nicht gefunden',
        'el' => 'διαδρομή για το url \'{$0}\' δεν βρέθηκε',
        'es' => 'la ruta de la dirección url \'{$0}\' no se encuentra',
        'et' => 'marsruut url \'{$0}\' ei leitud',
        'fi' => 'reitti url " {$0}\' ei löydy',
        'fr' => 'route de l\'url de \'{$0}\' ne trouve pas',
        'hu' => 'útvonal url \'{$0}\' nem található',
        'it' => 'percorso di url \'{$0}\' non trovato',
        'lt' => 'maršrutas " url " {$0}\' nerasta',
        'lv' => 'maršruts url \'{$0}\' nav atrasts',
        'mk' => 'пат за url \'{$0}\' не е пронајден',
        'nl' => 'route voor url \'{$0}\' niet gevonden',
        'no' => 'ruten for url \'{$0}\' ble ikke funnet',
        'pt' => 'encaminhar para a url \'{$0}\' não encontrado',
        'ru' => 'маршрут для url \'{$0}\' не найден',
        'sk' => 'trasy pre adresu url, \'{$0}\' nebol nájdený',
        'sl' => 'pot za url \'{$0}\' ni mogoče najti',
        'sq' => 'rruga për url \'{$0}\' nuk u gjet',
        'sv' => 'rutten för url \'{$0}\' hittades inte',
        'tr' => 'url route{$0} \'\' bulunamadı ',
        'uk' => 'маршрут для url \'{$0}\' не знайдений',
    ],
];