<?php
return [
    'File {$0} not found' => [
        'en' => 'File {$0} not found',
    ],
    'Class {$0} not found' => [
        'en' => 'Class {$0} not found',
    ],
    'Files for {$0} not found' => [
        'en' => 'Files for {$0} not found',
        'be' => 'Файлы для {$0} не знойдзены',
        'ca' => 'Arxius per {$0} no s\'ha trobat',
        'cs' => 'Soubory pro {$0} nebyl nalezen',
        'da' => 'Filer for {$0} blev ikke fundet',
        'de' => 'Dateien {$0} nicht gefunden',
        'el' => 'Αρχεία για {$0} δεν βρέθηκε',
        'es' => 'Archivos por {$0} no se encuentra',
        'et' => 'Failid {$0} ei leitud',
        'fi' => 'Tiedostot {$0} ei löydy',
        'fr' => 'Les fichiers de {$0} introuvable',
        'hu' => 'Fájlok {$0} nem található',
        'it' => 'File {$0} non trovato',
        'lt' => 'Failus {$0} nerastas',
        'lv' => 'Failus {$0} nav atrasts',
        'mk' => 'Датотеки за {$0} не е пронајдена',
        'nl' => 'Bestanden voor {$0} is niet gevonden',
        'no' => 'Filer for {$0} finnes ikke',
        'pt' => 'Arquivos para {$0} não encontrado',
        'ru' => 'Файлы для {$0} не найден',
        'sk' => 'Súbory na {$0} nenašiel',
        'sl' => 'Datoteke za {$0} ni mogoče najti',
        'sq' => 'Dosjet për {$0} nuk u gjet',
        'sv' => 'Filer för {$0} hittades inte',
        'tr' => '{$0} bulunamadı dosyaları ',
        'uk' => 'Файли для {$0} не знайдено',
    ],
    'File {$0} exists, but class {$1} not found' => [
        'en' => 'File {$0} exists, but class {$1} not found',
    ],
];