<?php
return [
    'Model class {$0} not found' => [
        'ru' => 'Model class {$0} not found',
    ],
    'Field {$0} not found in Model {$1}' => [
        'ru' => 'Field {$0} not found in Model {$1}',
    ],
    'Could not set value: Field "{$0}" not found in Model "{$1}"' => [
        'en' => 'Could not set value: Field "{$0}" not found in Model "{$1}"',
        'be' => 'Не ўдалося задаць значэнне поля "{$0}" ня знойдзены ў мадэлі "{$1}"',
        'ca' => 'No pogueren valor: Camp "{$0}" no s\'ha trobat en el Model de "{$1}"',
        'cs' => 'Nelze nastavit hodnoty: Pole "{$0}" nelze nalézt v Modelu "{$1}"',
        'da' => 'Kunne ikke indstille værdien: Området "{$0}" findes ikke i Modellen "{$1}"',
        'de' => 'Könnte nicht festgelegt Wert: - Feld "{$0}" wurde nicht gefunden " im Modell "{$1}"',
        'el' => 'Δεν θα μπορούσε να οριστεί τιμή: Πεδίο "{$0}" δεν βρέθηκε στο Μοντέλο "{$1}"',
        'es' => 'No se pudo establecer el valor del Campo "{$0}" no se encuentra en el Modelo de "{$1}"',
        'et' => 'Ei saanud seadistatud väärtus: Väli "{$0}" ei leitud Mudel "{$1}"',
        'fi' => 'Ei voinut asettaa arvo: - Kenttään "{$0}" ei löydy Malli "{$1}"',
        'fr' => 'Ne pouvait pas définir la valeur: le Champ "{$0}" n\'est pas trouvée dans le Modèle "{$1}"',
        'hu' => 'Nem tudta beállított érték: Mező "{$0}" nem található a Modell "{$1}"',
        'it' => 'Non può impostare il valore: il Campo "{$0}" non trovato nel Modello "{$1}"',
        'lt' => 'Nebuvo nustatyta vertė: Lauko "{$0}" nerastas Modelis "{$1}"',
        'lv' => 'Nevarēja iestatīt vērtību Laukā kam: "{$0}" nav atrasts Modelis "{$1}"',
        'mk' => 'Не можеше да се постави вредност: Field") {$0}" не се најде во Модел "{$1}"',
        'nl' => 'Kan niet worden ingesteld waarde: Veld "{$0} \' niet gevonden in het Model van "{$1}"',
        'no' => 'Kunne ikke er satt verdi: Feltet "{$0}" ikke finnes i Modellen "{$1}"',
        'pt' => 'Não foi possível definir o valor do Campo "{$0}" não encontrado no Modelo "{$1}"',
        'ru' => 'Не удалось задать значение поля "{$0}" не найден в модели "{$1}"',
        'sk' => 'Nemohol nastavená hodnota: Pole "{$0}" nebol nájdený v Modeli "{$1}"',
        'sl' => 'Ni nastavljeno vrednost: Polje "{$0}", ne najdemo v Modelu "{$1}"',
        'sq' => 'Nuk mund të vlerës së caktuar: Fusha "{$0}" nuk e gjeti në Modelin "{$1}"',
        'sv' => 'Kunde inte inställt värde: "{$0}" inte finns i Modellen "{$1}"',
        'tr' => 'Değeri ayarlanamadı: "{$0}" Model bulunamadı "{$1}", Alan ',
        'uk' => 'Не вдалося встановити значення поля "{$0}" не знайдений в моделі "{$1}"',
    ],
    'field "{$0}" of model "{$1}" is null' => [
        'en' => 'field "{$0}" of model "{$1}" is null',
        'be' => 'поле "{$0}" мадэлі "{$1}" is null',
        'ca' => 'camp "{$0}" de model "{$1}" és nul',
        'cs' => 'pole "{$0}" model "{$1}" je null',
        'da' => 'feltet "{$0}" model "{$1}" er null',
        'de' => 'Feld "{$0}" Modell "{$1}" ist null',
        'el' => 'το πεδίο "{$0}" μοντέλο "{$1}" είναι null',
        'es' => 'campo "{$0}" de modelo "{$1}" es nulo',
        'et' => 'väli "{$0}" mudeli "{$1}" on null,',
        'fi' => '- kenttään "{$0}" malli "{$1}" on tyhjä',
        'fr' => 'le champ "{$0}" de modèle "{$1}" est null',
        'hu' => 'mező "{$0}" modell "{$1}" null',
        'it' => 'campo "{$0}" di modello "{$1}" non e \' null',
        'lt' => 'srityje "{$0}" modelis "{$1}" yra niekinis',
        'lv' => 'laukā "{$0}" modelis "{$1}" ir nulle',
        'mk' => 'поле "{$0}" на моделот "{$1}" е нула',
        'nl' => 'veld "{$0}" model "{$1}" is leeg',
        'no' => 'feltet "{$0}" modell "{$1}" er null',
        'pt' => 'o campo "{$0}" do modelo "{$1}" é nulo',
        'ru' => 'поле "{$0}" модели "{$1}" is null',
        'sk' => 'pole "{$0}" model "{$1}", je null',
        'sl' => 'polje "{$0}" model "{$1}" je nična',
        'sq' => 'fusha "{$0}" të modelit "{$1}" është null',
        'sv' => 'fältet "{$0}" modellen "{$1}" är null',
        'tr' => '"{$0}" model "{$1}" boş alan ',
        'uk' => 'поле "{$0}" моделі "{$1}" is null',
    ],
    'Model::__get: Foreign key is missing - {$0} in model {$1}' => [
        'en' => 'Model::__get: Foreign key is missing - {$0} in model {$1}',
        'ru' => 'Модель::__получить: внешний ключ отсутствует - {$0} в модели {$1}',
    ],
    'Error - Field {$0} not found in Model {$1}' => [
        'ru' => 'Error - Field {$0} not found in Model {$1}',
    ],
    'Error - field "{$0}" of model "{$1}" is null' => [
        'ru' => 'Error - field "{$0}" of model "{$1}" is null',
    ],
];