<?php
return [
    'Model prefixes not found. Add in module config or so: ' => [
        'en' => 'Model prefixes not found. Add in module config or so: ',
        'ru' => 'Модель приставки не нашли. Добавить в модуль config или так: ',
    ],
    'Table with name {$0} in scheme {$1} not belongs to module {$2}. Check module config (model prefixes)' => [
        'en' => 'Table with name {$0} in scheme {$1} not belongs to module {$2}. Check module config (model prefixes)',
        'ru' => 'Таблица с именем {$0} в схеме {$1} не принадлежит модуля {$2}. Проверьте модуль конфигурации (модели приставки)',
    ],
    'Data source keys not found. Add in module config or so: ' => [
        'en' => 'Data source keys not found. Add in module config or so: ',
        'ru' => 'Источник данных ключей не нашли. Добавить в модуль config или так: ',
    ],
    'Data source keys not found.' => [
        'en' => 'Data source keys not found.',
        'ru' => 'Источник данных ключей не нашли.',
    ],
    'Data source prefixes not found.' => [
        'en' => 'Data source prefixes not found.',
        'ru' => 'Источник данных префиксов не нашли.',
    ],
    'Data source prefixes for data source {$0} not found.' => [
        'en' => 'Data source prefixes for data source {$0} not found.',
        'ru' => 'Источник данных префиксов для источника данных {$0} не найден.',
    ],
    'Module alias {$0} not found in module config files' => [
        'en' => 'Module alias {$0} not found in module config files',
        'be' => 'Псеўданім модуля {$0} не знойдзена ў модулі config файлы',
        'ca' => 'Mòdul àlies {$0} no s\'ha trobat en el mòdul fitxers de configuració',
        'cs' => 'Modul alias {$0} nebyla nalezena v modulu konfigurační soubory',
        'da' => 'Modul alias {$0}, som ikke findes i modul config filer',
        'de' => 'Modul alias {$0} nicht gefunden in Modul config-Dateien',
        'el' => 'Μονάδα ψευδώνυμο {$0} δεν βρέθηκε στην ενότητα αρχεία config',
        'es' => 'Módulo alias {$0} no se encuentra en los archivos de configuración del módulo',
        'et' => 'Moodul nimega {$0} ei leitud moodul config failid',
        'fi' => 'Moduuli alias {$0} ei löydy moduuli config-tiedostoja',
        'fr' => 'Module alias {$0} introuvable dans le module des fichiers de configuration',
        'hu' => 'Modul alias {$0} nem található modul konfigurációs fájlok',
        'it' => 'Modulo alias {$0} non trovato nel file di configurazione del modulo',
        'lt' => 'Modulio alias {$0} nerastas modulio konfigūracijos failus',
        'lv' => 'Moduļa alias {$0} nav atrodama modulis config failiem',
        'mk' => 'Модул алијас {$0} не се најде во модул config датотеките',
        'nl' => 'Module alias {$0} is niet gevonden in de module configuratie bestanden',
        'no' => 'Modul alias {$0} finnes ikke i modul config filer',
        'pt' => 'Módulo alias {$0} não encontrado no módulo arquivos de configuração',
        'ru' => 'Псевдоним модуля {$0} не найдена в модуле config файлы',
        'sk' => 'Modul alias {$0} nie je nájdený v module konfiguračné súbory',
        'sl' => 'Modul alias {$0} ni mogoče najti v modulu nastavitvene datoteke',
        'sq' => 'Moduli pseudonim {$0} nuk gjendet në modul config files',
        'sv' => 'Modul alias {$0} inte finns i modulen config filer',
        'tr' => 'Modül {$0} module config dosyalarında bulunan diğer değil ',
        'uk' => 'Псевдонім модуля {$0} не знайдена в модулі config файли',
    ],
];