<?php
return [
    'fail' => [
        'en' => 'fail',
        'be' => 'fail',
        'ca' => 'falla',
        'cs' => 'nedaří',
        'da' => 'fail',
        'de' => 'fail',
        'el' => 'αποτυχία',
        'es' => 'fallar',
        'et' => 'ei',
        'fi' => 'epäonnistua',
        'fr' => 'échec',
        'hu' => 'sikertelen',
        'it' => 'esito negativo',
        'lt' => 'nepavyks',
        'lv' => 'fail',
        'mk' => 'пропадне',
        'nl' => 'mislukken',
        'no' => 'mislykkes',
        'pt' => 'falhar',
        'ru' => 'fail',
        'sk' => 'fail',
        'sl' => 'ne',
        'sq' => 'dështojnë',
        'sv' => 'misslyckas',
        'tr' => 'başarısız',
        'uk' => 'fail',
    ],
];