<?php
return [
    'Response broken. View not found {$0}' => [
        'en' => 'Response broken. View not found {$0}',
        'be' => 'Адказ зламаныя. Выгляд не знойдзены {$0}',
        'ca' => 'Resposta trencat. Vista de no trobar {$0}',
        'cs' => 'Odpověď rozbité. Výhled nebyl nalezen {$0}',
        'da' => 'Svar brudt. Se ikke fundet {$0}',
        'de' => 'Antwort gebrochen. View nicht gefunden {$0}',
        'el' => 'Απάντηση σπασμένα. Προβολή δεν βρέθηκε {$0}',
        'es' => 'Respuesta roto. Vista no encontrada {$0}',
        'et' => 'Vastuse katki. Vaadata ei leitud {$0}',
        'fi' => 'Vastaus rikki. Näkymä ei löydy {$0}',
        'fr' => 'Réponse cassé. Vue pas trouvé {$0}',
        'hu' => 'Válasz hibás. Nézet nem talált {$0}',
        'it' => 'Risposta rotto. Vista non trovato {$0}',
        'lt' => 'Atsako neveikia. Peržiūrėti nerasta {$0}',
        'lv' => 'Atbilde sadalīti. Skats nav atrasts {$0}',
        'mk' => 'Одговор скршени. Приказ не се најде {$0}',
        'nl' => 'Reactie gebroken. Niet gevonden {$0}',
        'no' => 'Svar brutt. Vis ikke funnet {$0}',
        'pt' => 'Resposta quebrado. Visão que não se encontra {$0}',
        'ru' => 'Ответ сломаны. Вид не найден {$0}',
        'sk' => 'Odpoveď nefunkčné. Zobraziť nenašiel {$0}',
        'sl' => 'Odgovor zlomljena. Pogled ne najdemo {$0}',
        'sq' => 'Përgjigje thyer. Pamja nuk është gjetur {$0}',
        'sv' => 'Svar bruten. Visa inte hittat {$0}',
        'tr' => 'Yanıt kırılmış. Görünüm bulunamadı {$0}',
        'uk' => 'Відповідь зламані. Вид не знайдено {$0}',
    ],
];