<?php
return [
    'Php: View {$0} not found. Trying generate template {$1}...' => [
        'ru' => 'Php: вид {$0} не найден. Пытаюсь создать шаблон {$1}...',
        'en' => 'Php: View {$0} not found. Trying generate template {$1}...',
        'be' => 'Php: выгляд {$0} не знойдзены. Спрабую стварыць шаблен {$1}...',
        'ca' => 'Php: Vista {$0} no s\'ha trobat. Intentant generar plantilla {$1}...',
        'cs' => 'Php: Zobrazit {$0} nebyl nalezen. Snaží vytvářet šablony {$1}...',
        'da' => 'Php: du kan få Vist {$0} kunne ikke findes. Forsøger at generere skabelonen {$1}...',
        'de' => 'Php: View {$0} wurde nicht gefunden. Versuchen generieren Vorlage {$1}...',
        'el' => 'Php: Προβολή {$0} δεν βρέθηκε. Προσπαθώντας δημιουργήσει πρότυπο {$1}...',
        'es' => 'Php: Ver {$0} no se encuentra. Tratando de generar plantilla {$1}...',
        'et' => 'Php: Vaade {$0} ei leitud. Püüdes luua malli {$1}...',
        'fi' => 'Php: Näytä {$0} ei löytynyt. Yrittää luoda malli {$1}...',
        'fr' => 'Php: Afficher {$0} est introuvable. Essayer de générer le modèle {$1}...',
        'hu' => 'Php: Nézet {$0} nem található. Próbálunk generálni sablon {$1}...',
        'it' => 'Php: Vista {$0} non trovato. Tentando di generare template {$1}...',
        'lt' => 'Php: Peržiūrėti {$0} nerastas. Bando sukurti šabloną {$1}...',
        'lv' => 'Php: Skatīt {$0} nav atrasts. Mēģina radīt veidni {$1}...',
        'mk' => 'Php: Приказ {$0} не е пронајден. Обидувајќи се генерираат шаблонот {$1}...',
        'nl' => 'Php: Bekijk {$0} is niet gevonden. Proberen te genereren sjabloon {$1}...',
        'no' => 'Php: Vis {$0} ikke funnet. Prøver generere malen {$1}...',
        'pt' => 'Php: Ver {$0} não encontrado. Tentando gerar modelo {$1}...',
        'sk' => 'Php: Pohľad {$0} nie nájsť. Snaží vytvárať šablóny {$1}...',
        'sl' => 'Php: Prikaz {$0} ni mogoče najti. Poskuša ustvariti predlogo {$1}...',
        'sq' => 'Php: Pamje {$0} nuk është gjetur. Duke u përpjekur të gjeneruar template {$1}...',
        'sv' => 'Php: Visa {$0} hittades inte. Försöker skapa mallen {$1}...',
        'tr' => 'Php: Görünüm {$0} bulunamadı. Şablonu {$1} oluşturmak çalışıyorum...',
        'uk' => 'Php: вид {$0} не знайдено. Намагаюся створити шаблон {$1}...',
    ],
    'Fetch template "{$0}" failed' => [
        'en' => 'Fetch template "{$0}" failed',
        'ru' => 'Извлечение шаблона "{$0}" не удалось',
    ],
    'Twig: View {$0} not found. Trying generate template {$1}...' => [
        'en' => 'Twig: View {$0} not found. Trying generate template {$1}...',
        'ru' => 'Веточка: смотреть {$0} не найдена. Пытаюсь создать шаблон {$1}...',
    ],
];